# Generated by Django 2.2.2 on 2022-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20220304_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ds',
            field=models.BigIntegerField(default=1647424458.0, verbose_name='时间戳'),
        ),
    ]
