# Generated by Django 2.2.2 on 2022-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20220316_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ds',
            field=models.BigIntegerField(default=1648379850.0, verbose_name='时间戳'),
        ),
    ]
