# Generated by Django 2.2.2 on 2022-03-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20220330_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ds',
            field=models.BigIntegerField(default=1648645422.0, verbose_name='时间戳'),
        ),
    ]
