# Generated by Django 2.2.2 on 2022-03-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to='avatars/', verbose_name='用户头像地址')),
            ],
            options={
                'verbose_name_plural': '用户头像',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='http://127.0.0.1:8080/media/avatars/', verbose_name='头像'),
        ),
    ]
