# Generated by Django 2.2.2 on 2022-03-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220330_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='url',
            field=models.FileField(default='人物.png', upload_to='avatars/', verbose_name='用户头像地址'),
        ),
    ]
